<nav id="breadcrumb">
    <p>YOU ARE HERE</p>

    <?php
    $this->Breadcrumbs->add(_('LISTS'), ['controller' => 'releases', 'action' => 'index']);
    $this->Breadcrumbs->add(strtoupper($submission->information_list_name), ['controller' => 'listings', 'action' => 'list', strtolower($submission->information_list_name), 'io500']);
    $this->Breadcrumbs->add(strtoupper($submission->information_system), ['controller' => 'submissions', 'action' => 'view', $submission->id]);
    $this->Breadcrumbs->add(_('REPRODUCIBILITY'), ['controller' => 'questionnaires', 'action' => 'view', $submission->id]);

    echo $this->Breadcrumbs->render([], ['separator' => ' / ']);
    ?>
</nav>

<div class="row">
    <div class="column-responsive column-80">
        <div class="submissions view content">
            <h2>
                <div class="badge badge-<?php echo $questionnaire->reproducibility_score_id; ?>"></div>

                <?php echo h($submission->information_system) ?>
            </h2>
        </div>
    </div>
</div>

<div class="both"></div>

<?php echo $this->Form->create($questionnaire); ?>

<div class="row">
    <div class="column-responsive column-80">
        <div class="questionnaires form content">
            <fieldset>
                <legend>System Purpose</legend>

                <p>
                    Please describe the purpose and general usage of the submitted system.&nbsp; This would include the types of typical applications it supports (e.g., defense applications, molecular dynamics, benchmarking, system test, systems research), and the general use and purpose of the data generated by the applications running on it.
                </p>

                <?php
                echo $this->Form->control('system_purpose', [
                    'label' => false,
                    'required' => true,
                    'class' => 'tinymce'
                ]);
                ?>
            </fieldset>

            <fieldset>
                <legend>Availability</legend>

                <p>
                    Please provide the deployment timeframe of the submitted system, or for on-demand cloud systems, the general period over which it is deployed and destroyed.
                </p>

                <p>
                    Please describe the availability of the system to users and who are its set of most regular users.
                </p>

                <?php
                echo $this->Form->control('availability', [
                    'label' => false,
                    'required' => true,
                    'class' => 'tinymce'
                ]);
                ?>
            </fieldset>

            <fieldset>
                <legend>Storage System Software</legend>

                <p>
                    Please describe the purpose and general usage of the submitted system.&nbsp; This would include the types of typical applications it supports (e.g., defense applications, molecular dynamics, benchmarking, system test, systems research), and the general use and purpose of the data generated by the applications running on it.
                </p>

                <p>
                    How is this storage software available? (e.g., commercially, open-source, not publicly available) Note that if the storage software is not open-source or commercially available, then a general description would be requested, but this would limit the submission’s reproducibility score.
                </p>

                <p>
                    Can anyone download/purchase this software?
                </p>

                <p>
                    List either product webpage or open-source repo of the exact software used in IO500.
                </p>

                <p>
                    Give any and all additional details of this specific storage deployment: (e.g., type of storage server product such IBM ESS or DDN SFA400X2, use of Ext4 or some other file system on each storage node, dual connected storage media to storage servers).
                </p>

                <?php
                echo $this->Form->control('storage_system_software', [
                    'label' => false,
                    'required' => true,
                    'class' => 'tinymce'
                ]);
                ?>
            </fieldset>

            <fieldset>
                <legend>Runtime Environment</legend>

                <p>
                    State here that you provided all scripts/documentation that would allow someone else to reproduce your environment and attempt to achieve a similar IO500 score as the submitted system.
                </p>

                <p>
                    <strong>NOTE</strong>: provide all files/documentation/scripts that would enable a user to build your environment and deploy the custom scripts, software, or config files once they have obtained the appropriate storage system hardware and software. These may be included into the io500.tgz or into the extraCodes upload on the submission form.
                </p>

                <p>
                    Several examples include:                    
                </p>

                <ul>
                    <li>
                        Commands used to set striping information (either for the entire system or for particular directories)
                    </li>
                    <li>
                        File system config and tuning information (or a reason why this is not available due to lack of root access, etc) on each node type (e.g., non-default config parameters on all three types of Lustre  nodes: MDS, OSS, and client)
                    </li>
                    <li>
                        Any additional scripts utilized that impact IO500 execution beyond the io500 config file. For example, with IBM Spectrum Scale, the output of mmlsconfig, mmlscluster, mmlsfs, and mmlsfileset commands (and possibly even a dump of the configuration if possible). Each file system probably has similar type of config/tuning information that would need to be shared for a user to fully reproduce the environment.
                    </li>
                </ul>

                <?php
                echo $this->Form->control('runtime_environment', [
                    'label' => false,
                    'required' => true,
                    'class' => 'tinymce'
                ]);
                ?>
            </fieldset>

            <fieldset>
                <legend>Fault Tolerance Mechanisms</legend>

                <p>
                    Does your system have a single point of failure as defined by “Definition 7” of a Production System? Please describe all mechanisms that provide fault tolerance for the submitted storage system.  Be specific to your submission, not general storage system capabilities.
                </p>

                <ul>
                    <li>
                        Power  (For example, can power failure of a node or rack bring down the storage system?)
                    </li>
                    <li>
                        Networking (For example, can failure of a single NIC bring down the storage system? Remember that any networking failure that brings down multiple nodes is acceptable)
                    </li>
                    <li>
                        Inter storage data and metadata server (For example, what type of data protection mechanism does the storage system use to keep operating during node failures, e.g., active-active servers, client-directed RAID, declustered RAID, erasure-coding, 3-way replication)
                    </li>
                    <li>
                        Intra storage data and metadata server storage media (For example, how does the storage eysstem protect against fiailure of a single storage device within a node, e.g., raid5)
                    </li>
                </ul>

                <p>
                    Please list any additional information needed to determine whether this system has a single point of failure.
                </p>

                <?php
                echo $this->Form->control('fault_tolerance_mechanisms', [
                    'label' => false,
                    'required' => true,
                    'class' => 'tinymce'
                ]);
                ?>
            </fieldset>

            <fieldset>
                <legend>Execution</legend>

                <p>
                    Please provide a description of how the IO500 benchmark was executed, e.g., via system scheduler (e.g., SLURM) to run a job on the compute cluster, which initially ran a setup process to configure the client and file system, and then started the full benchmark.
                </p>

                <p>
                    During the IO500 benchmark execution was the system entirely dedicated to running the benchmark or were there other jobs running in the same cluster and storage system?
                </p>

                <?php
                echo $this->Form->control('execution', [
                    'label' => false,
                    'required' => true,
                    'class' => 'tinymce'
                ]);
                ?>
            </fieldset>

            <fieldset>
                <legend>Caching</legend>

                <p>
                    Please describe all caching mechanisms in client/server that were utilized during the IO500 run. This could include caching in any storage medium (e.g., SSD, RAM).
                </p>

                <p>
                    A few examples would include:
                </p>

                <ul>
                    <li>Client data/metadata caching (in Linux page cache or in other memory cache)</li>
                    <li>Client side NVMe read-only data cache</li>
                    <li>Storage server metadata/data caching in RAM</li>
                    <li>Storage controller caching</li>
                    <li>RAID card caching</li>
                </ul>

                <?php
                echo $this->Form->control('caching', [
                    'label' => false,
                    'required' => true,
                    'class' => 'tinymce'
                ]);
                ?>
            </fieldset>

            <fieldset>
                <legend>Data Source</legend>

                <p>
                    Is the submitted system a stand-alone storage system or an acceleration layer in front of another storage system that is the source of truth for all application data? This question relates to whether the submitted system is a burst buffer layered on primary storage or primary storage itself.
                </p>

                <?php
                echo $this->Form->control('data_source', [
                    'label' => false,
                    'required' => true,
                    'class' => 'tinymce'
                ]);
                ?>
            </fieldset>

            <fieldset>
                <legend>Trust</legend>

                <p>
                    Please describe any steps taken to ensure that the results are trustworthy.
                </p>

                <ul>
                    <li>Did you run the benchmark multiple times and get similar scores?</li>
                    <li>Did you validate the score is below the physical capabilities of the deployed hardware?</li>
                    <li>How did you validate that the storage system follows the <a href="https://io500.org/rules-submission" target="_blank">IO500 rules</a> regarding persistence, which states, "All data must be written to persistent storage within the measured time for the individual benchmark, e.g. if a file system caches data, it must ensure that data is persistently stored before acknowledging the close"?</li>
                </ul>

                <?php
                echo $this->Form->control('trust', [
                    'label' => false,
                    'required' => true,
                    'class' => 'tinymce'
                ]);
                ?>
            </fieldset>
        </div>
    </div>
</div>

<?php echo $this->Form->end(); ?>

<script src="https://cdn.tiny.cloud/1/1q5sjjedyv15tfpn9b7cvojp4i72ahfneyqj7yrfu771hcu1/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>

<script type="text/javascript">
    var t_editors;

    editors = tinymce.init({
        skin: 'outside',
        icons: 'small',
        statusbar: false,
        menubar: false,
        selector: 'textarea',
        height: 300,
        readonly: 1,
        plugins: 'image link lists searchreplace table wordcount',
        toolbar: false,
        content_css: ['/io-500-hub/css/editor.css']
    }).then(function(editors) {
        t_editors = editors;
    });
</script>