-- create the SCC list type

INSERT INTO `types` (`id`, `name`, `url`) VALUES (NULL, 'SCC', 'scc');

-- create a release for SCC of SC19

INSERT INTO `listings` (`id`, `type_id`, `release_id`, `description`) VALUES (NULL, '5', '5', '<p>This is the result of the Student Cluster Competition at Supercomputing 2019. These results are obtained with slightly relaxed rules, i.e., they are not directly comparable to results reported in the other IO500 lists.</p>');

-- insert the submission records for SCC

    INSERT INTO submissions
    (
	release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
        5,
        'Tsinghua',
        'Tsinghua',
        'Intel',
        'ext4',
        '1',
        '36',
        '30.56',
        '3.08',
        '303.12',
        'zip',
        'SCC19',
        '2019-11-scc-1',
        'Tsinghua',
        '2019-11-19',
        '',
        '',
        '',
        '',
        '',
        '36',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '1',
        'NVMe',
        '6400',
        '',
        '',
        '',
        '',
        '',
        '',
        '110.60',
        '4.16',
        '6.15',
        '0.89',
        '3.94',
        '326.96',
        '806.44',
        '149.81',
        '71.21',
        '329.08',
        '787.61',
        '51.83',
        '1886.47',
        '-',
        '-',
        '-',
        'VALID'
    );



    INSERT INTO submissions
    (
        release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
        5,
        '',
        'Nanyang',
        '',
        '',
        '1',
        '48',
        '28.28',
        '4.14',
        '193.21',
        'zip',
        'SCC19',
        '2019-11-scc-11',
        'Nanyang',
        '2019-11-19',
        '',
        '',
        '',
        '',
        '',
        '48',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '2',
        '2',
        'NVMe',
        '',
        'Samsung PM1725',
        'Infiniband EDR',
        'ext4',
        '',
        '',
        '',
        '90.39',
        '4.50',
        '13.23',
        '1.23',
        '4.02',
        '319.20',
        '116.60',
        '109.83',
        '73.53',
        '390.10',
        '398.03',
        '66.87',
        '622.27',
        '-',
        '-',
        '-',
        'VALID'
    );



    INSERT INTO submissions
    (
        release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
        5,
        'Hammertime',
        'Purdue',
        '',
        '',
        '5',
        '80',
        '26.08',
        '9.80',
        '69.40',
        'zip',
        'SCC19',
        '2019-11-scc-14',
        'Purdue',
        '2019-11-20',
        '',
        '',
        '',
        '',
        '',
        '16',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '5',
        '12',
        'NVMe U.2',
        '19660',
        '',
        'HDR100 ',
        '',
        '',
        '',
        '',
        '60.88',
        '28.12',
        '27.50',
        '1.50',
        '7.95',
        '106.94',
        '385.44',
        '91.66',
        '7.16',
        '28.17',
        '53.76',
        '11.84',
        '1110.46',
        '-',
        '-',
        '-',
        'VALID'
    );



    INSERT INTO submissions
    (
        release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
        5,
        'COO',
        'Shanghai Tech University',
        'Intel',
        'local file system',
        '1',
        '36',
        '20.42',
        '2.62',
        '159.38',
        'zip',
        'SCC19',
        '2019-11-scc-9',
        'Shanghai Tech University',
        '2019-11-20',
        '',
        '',
        '',
        'extfs',
        '4',
        '36',
        'CentOS',
        '7.7',
        '3.10',
        '1',
        '1',
        'NVMe',
        '384GB',
        'NVMe',
        'Infiniband',
        '',
        '',
        '1',
        '1',
        '3DXPNVMeSSD',
        '384GB',
        'NVMe',
        'Infiniband',
        '',
        '',
        '',
        '',
        '68.22',
        '3.65',
        '6.11',
        '0.69',
        '3.06',
        '67.88',
        '932.26',
        '137.00',
        '38.59',
        '127.59',
        '168.05',
        '71.82',
        '808.11',
        '-',
        '-',
        '-',
        'VALID'
    );



    INSERT INTO submissions
    (
        release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
        5,
        '',
        'ETH Zurich',
        'Intel',
        '',
        '1',
        '56',
        '19.59',
        '3.24',
        '118.57',
        'zip',
        'SCC19',
        '2019-11-scc-2',
        'ETH Zurich',
        '2019-11-19',
        '',
        '',
        '',
        '',
        '',
        '56',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '1',
        '8',
        'Intel Optane P4800X',
        '3000',
        '',
        '',
        'xfs',
        '',
        '',
        '',
        '60.13',
        '6.80',
        '16.30',
        '0.38',
        '2.61',
        '258.05',
        '1584.29',
        '325.31',
        '7.70',
        '33.56',
        '46.84',
        '9.66',
        '2512.31',
        '-',
        '-',
        '-',
        'VALID'
    );



    INSERT INTO submissions
    (
        release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
        5,
        'Peking',
        'Peking',
        '',
        'ext4',
        '1',
        '16',
        '16.21',
        '2.55',
        '103.25',
        'zip',
        'SCC19',
        '2019-11-scc-8',
        'Peking',
        '2019-11-18',
        '',
        '',
        '',
        '',
        '',
        '16',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '8',
        'NVMe U.2',
        '16000',
        '',
        '',
        '',
        '',
        '',
        '',
        '50.61',
        '1.38',
        '17.84',
        '0.80',
        '2.15',
        '91.99',
        '556.40',
        '210.01',
        '26.57',
        '44.36',
        '62.48',
        '37.20',
        '438.53',
        '-',
        '-',
        '-',
        'VALID'
    );



    INSERT INTO submissions
    (
        release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
        5,
        '',
        'FAU',
        '',
        'ext4',
        '1',
        '2',
        '13.82',
        '2.02',
        '94.41',
        'zip',
        'SCC19',
        '2019-11-scc-12',
        'FAU',
        '2019-11-20',
        '',
        '',
        '',
        '',
        '',
        '2',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '2',
        'NVMe',
        '7400',
        '',
        '',
        '',
        '',
        '',
        '',
        '44.17',
        '1.96',
        '3.49',
        '0.78',
        '3.15',
        '90.44',
        '213.11',
        '83.25',
        '50.97',
        '15.32',
        '171.56',
        '67.44',
        '435.38',
        '-',
        '-',
        '-',
        'VALID'
    );



    INSERT INTO submissions
    (
        release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
        5,
        '',
        'University of Illinois at Urbana-Champaign',
        '',
        'GPFS',
        '1',
        '32',
        '12.70',
        '6.51',
        '24.78',
        'zip',
        'SCC19',
        '2019-11-scc-13',
        'UIUC',
        '2019-11-20',
        '',
        '',
        '',
        '',
        '',
        '32',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '2',
        'NVMe',
        '6000',
        '',
        '',
        'GPFS',
        '',
        '',
        '',
        '26.73',
        '14.12',
        '22.15',
        '1.04',
        '5.51',
        '58.88',
        '86.50',
        '39.08',
        '10.18',
        '5.75',
        '10.40',
        '2.50',
        '467.92',
        '-',
        '-',
        '-',
        'VALID'
    );



    INSERT INTO submissions
    (
        release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
        5,
        'NTHU-SCC',
        'NTHU',
        '',
        '',
        '1',
        '40',
        '9.40',
        '1.05',
        '84.16',
        'zip',
        'SCC19',
        '2019-11-scc-6',
        'NTHU',
        '2019-11-19',
        '',
        '2019-11-18',
        '2019-11-18',
        '',
        '',
        '40',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '1',
        '4',
        'SSD',
        '754G',
        'SATA',
        'IB-EDR',
        'ext4',
        'CentOS 7.6 1810',
        '',
        '',
        '32.89',
        '0.88',
        '1.92',
        '0.50',
        '1.43',
        '39.23',
        '862.40',
        '76.16',
        '25.80',
        '51.63',
        '71.31',
        '31.01',
        '331.73',
        '-',
        '-',
        '-',
        'VALID'
    );



    INSERT INTO submissions
    (
        release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
        5,
        'Cosmo',
        'Tennessee',
        'Cray',
        '/dev/md0',
        '1',
        '4',
        '8.97',
        '1.85',
        '43.39',
        'zip',
        'SCC19',
        '2019-11-scc-4',
        'Tennessee',
        '2019-11-20',
        '',
        '',
        '',
        '',
        '',
        '4',
        'CentOS',
        '7.6',
        '3.10.0-1062.4.1.el7.x86_64',
        '1',
        '2',
        'NVMe',
        '1.8T',
        'NVMe',
        'IB-EDR',
        '',
        '',
        '',
        '',
        'NVMe',
        '',
        'NVMe',
        'IB-EDR',
        '',
        'CentOS 7.6',
        '',
        '',
        '25.55',
        '1.93',
        '4.94',
        '0.55',
        '2.26',
        '59.16',
        '121.31',
        '43.75',
        '11.98',
        '22.74',
        '42.76',
        '13.39',
        '256.48',
        '-',
        '-',
        '-',
        'VALID'
    );



    INSERT INTO submissions
    (
        release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
        5,
        'Daemon Deacons',
        'Wake Forest University',
        '',
        '',
        '1',
        '1',
        '5.44',
        '0.98',
        '30.21',
        'zip',
        'SCC19',
        '2019-11-scc-10',
        'Wake Forest University',
        '2019-11-20',
        '',
        '',
        '',
        '',
        '',
        '1',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '1',
        '2',
        'SSD',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '16.23',
        '0.99',
        '1.03',
        '1.03',
        '0.88',
        '14.43',
        '58.80',
        '35.15',
        '12.77',
        '8.57',
        '49.09',
        '24.06',
        '179.95',
        '-',
        '-',
        '-',
        'VALID'
    );



    INSERT INTO submissions
    (
        release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
        5,
        'Moniuszko',
        'University of Warsaw',
        'Intel Corporation',
        'Distributed File System',
        '2',
        '80',
        '4.95',
        '1.33',
        '18.38',
        'zip',
        'SCC19',
        '2019-11-scc-15',
        'WarsawTeam',
        '2019-11-20',
        '',
        '2019-10-01',
        '',
        'MooseFS',
        '3.0.107',
        '40',
        'CentOS',
        '7.6',
        'Linux moniuszko-n1.icm.edu.pl 3.10.0-1062.1.2.el7.x86_64',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '3',
        '3',
        'SSD-NVMe',
        '384',
        'PCIe',
        'IB-EDR',
        'MooseFS 3.0.107',
        'CentOS 7.6',
        '',
        '',
        '12.92',
        '3.83',
        '3.36',
        '0.42',
        '0.58',
        '20.31',
        '47.28',
        '24.29',
        '5.85',
        '7.09',
        '9.47',
        '4.82',
        '295.61',
        '-',
        '-',
        '-',
        'VALID'
    );



    INSERT INTO submissions
    (
        release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
        5,
        'DAWGZ cluster',
        'University of Washington',
        'Samsung',
        'ext',
        '1',
        '32',
        '4.39',
        '0.25',
        '77.92',
        'zip',
        'SCC19',
        '2019-11-scc-5',
        'University of Washington SCC-SC19 team',
        '2019-11-19',
        '',
        '',
        '',
        'ext4',
        '4',
        '32',
        'CentOS',
        '7',
        '3.10.0-1062.4.1.el7.x86_64',
        '0',
        'n/a',
        'n/a',
        'n/a',
        'n/a',
        'n/a',
        'n/a',
        'n/a',
        '1',
        '1',
        'SSD',
        '256GB',
        'SATA',
        'Infiniband',
        'ext4',
        'CentOS 7',
        '',
        '',
        '19.29',
        '0.19',
        '0.53',
        '0.07',
        '0.52',
        '46.36',
        '368.26',
        '78.54',
        '14.87',
        '45.01',
        '82.10',
        '21.71',
        '849.36',
        '-',
        '-',
        '-',
        'VALID'
    );



    INSERT INTO submissions
    (
        release_id,
        information_system,
        information_institution,
        information_storage_vendor,
        information_filesystem_type,
        information_client_nodes,
        information_client_total_procs,
        previous_io500_score,
        io500_bw,
        io500_md,
        information_data,
        information_list_name,
        information_identifier,
        information_submitter,
        information_submission_date,
        information_embargo_end_date,
        information_storage_install_date,
        information_storage_refresh_date,
        information_filesystem_name,
        information_filesystem_version,
        information_client_procs_per_node,
        information_client_operating_system,
        information_client_operating_system_version,
        information_client_kernel_version,
        information_md_nodes,
        information_md_storage_devices,
        information_md_storage_type,
        information_md_volatile_memory_capacity,
        information_md_storage_interface,
        information_md_network,
        information_md_software_version,
        information_md_operating_system_version,
        information_ds_nodes,
        information_ds_storage_devices,
        information_ds_storage_type,
        information_ds_volatile_memory_capacity,
        information_ds_storage_interface,
        information_ds_network,
        information_ds_software_version,
        information_ds_operating_system_version,
        information_note,
        information_best,
        io500_tot_iops,
        ior_easy_write,
        ior_easy_read,
        ior_hard_write,
        ior_hard_read,
        mdtest_easy_write,
        mdtest_easy_stat,
        mdtest_easy_delete,
        mdtest_hard_write,
        mdtest_hard_read,
        mdtest_hard_stat,
        mdtest_hard_delete,
        find_easy,
        marker_score,
        marker_md,
        storage_data,
        status
    )
    VALUES
    (
	5,
        'Shanghai Jiao Tong',
        'Shanghai Jiao Tong',
        'Inspur',
        '',
        '1',
        '2',
        '3.28',
        '1.19',
        '9.05',
        'zip',
        'SCC19',
        '2019-11-scc-7',
        'Shanghai Jiao Tong',
        '2019-11-20',
        '',
        '',
        '',
        '',
        '',
        '2',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '7.75',
        '1.62',
        '3.66',
        '0.37',
        '0.91',
        '5.62',
        '22.03',
        '7.53',
        '3.44',
        '4.80',
        '12.03',
        '4.41',
        '55.14',
        '-',
        '-',
        '-',
        'VALID'
    );

-- create the table for the SCC list

CREATE TABLE `list_sc19_scc` (
  `id` SERIAL NOT NULL AUTO_INCREMENT,
  `listing_id` int(11) NOT NULL,
  `submission_id` int(11) NOT NULL,
  `score` double NOT NULL
);

-- create the entries for the SCC list

INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '497', '30.56');


INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '498', '28.28');


INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '499', '26.08');


INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '500', '20.42');


INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '501', '19.59');


INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '502', '16.21');


INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '503', '13.82');


INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '504', '12.70');


INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '505', '9.40');


INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '506', '8.97');


INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '507', '5.44');


INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '508', '4.95');


INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '509', '4.39');


INSERT INTO list_sc19_scc (listing_id, submission_id, score)
VALUES ('26', '510', '3.28');


-- remove existing view
DROP VIEW listings_submissions;

-- update view
CREATE VIEW listings_submissions AS

SELECT * FROM list_sc17_io500
UNION ALL

SELECT * FROM list_isc18_io500
UNION ALL

SELECT * FROM list_isc19_10node
UNION ALL
SELECT * FROM list_isc19_full
UNION ALL
SELECT * FROM list_isc19_io500
UNION ALL

SELECT * FROM list_isc20_10node
UNION ALL
SELECT * FROM list_isc20_full
UNION ALL
SELECT * FROM list_isc20_historical
UNION ALL
SELECT * FROM list_isc20_io500
UNION ALL

SELECT * FROM list_sc18_10node
UNION ALL
SELECT * FROM list_sc18_io500
UNION ALL
SELECT * FROM list_sc18_star_10node
UNION ALL
SELECT * FROM list_sc18_star_io500
UNION ALL

SELECT * FROM list_sc19_10node
UNION ALL
SELECT * FROM list_sc19_full
UNION ALL
SELECT * FROM list_sc19_historical
UNION ALL
SELECT * FROM list_sc19_io500
UNION ALL
SELECT * FROM list_sc19_scc
UNION ALL

SELECT * FROM list_sc20_10node
UNION ALL
SELECT * FROM list_sc20_full
UNION ALL
SELECT * FROM list_sc20_historical
UNION ALL
SELECT * FROM list_sc20_io500
UNION ALL

SELECT * FROM list_isc21_10node
UNION ALL
SELECT * FROM list_isc21_io500;




